# Generated by Django 4.0.4 on 2022-05-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dateofbirth', models.DateField()),
                ('St_ID', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('level', models.CharField(blank=True, choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'In Active')], max_length=10, null=True)),
                ('department', models.CharField(blank=True, choices=[('general', 'General'), ('is', 'Information System'), ('cs', 'Computer Science'), ('ai', 'Artificial Intelligence'), ('ds', 'Decision Support'), ('it', 'Information Tecnology')], max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
