# Generated by Django 4.0.4 on 2022-05-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signin',
            new_name='login',
        ),
    ]
