# Generated by Django 4.0.4 on 2022-05-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_signin_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudents',
            old_name='email',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='addstudents',
            old_name='firstname',
            new_name='lname',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='St_ID',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='department',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='level',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='status',
        ),
    ]
