# Generated by Django 4.0.4 on 2022-05-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_email_addstudents_fname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddStudents',
            new_name='Add',
        ),
    ]
