# Generated by Django 4.0.4 on 2022-05-24 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_addstudents_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
