# Generated by Django 4.0.4 on 2022-05-24 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
