# Generated by Django 4.0.4 on 2022-05-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_add_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dateofbirth', models.DateTimeField(auto_now_add=True)),
                ('St_ID', models.IntegerField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Add',
        ),
    ]
