# Generated by Django 4.0.4 on 2022-05-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_addstudentt_delete_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentt',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
