# Generated by Django 4.0.4 on 2022-05-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_addstudentt_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentt',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
