# Generated by Django 4.0.4 on 2022-05-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_addstudentt_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentt',
            name='level',
            field=models.CharField(blank=True, choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addstudentt',
            name='Gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=50, null=True),
        ),
    ]
