# Generated by Django 4.0.4 on 2022-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_addstudentt_level_alter_addstudentt_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentt',
            name='department',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('is', 'Information System'), ('cs', 'Computer Science'), ('ai', 'Artificial Intelligence'), ('ds', 'Decision Support'), ('it', 'Information Tecnology')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addstudentt',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'In Active')], max_length=50, null=True),
        ),
    ]
